site:
  title: Meridian
  start_page: meridian::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_path: docs
ui:
  bundle:
    url: https://github.com/opennms-forge/antora-ui-opennms/releases/download/v2.0.0/ui-bundle.zip
asciidoc:
  attributes:
    experimental: true
    stem: latexmath
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    source-language: asciidoc@
    distribution: 'Meridian'
    tabs: tabs
  extensions:
    - ./docs/lib/tabs-block.js
output:
  clean: true
  dir: ./public
  destinations:
  - provider: fs
  - provider: archive
