commands:
  run-smoke-tests:
    description: "Run the smoke tests"
    parameters:
      suite:
        default: core
        type: string
    steps:
      - run:
          name: Enable swap
          command: |
            sudo fallocate -l 8G /swapfile
            sudo chmod 600 /swapfile
            sudo mkswap /swapfile
            sudo swapon /swapfile
            sudo sysctl vm.swappiness=5
            cat /proc/sys/vm/swappiness
      - load-oci:
          key: horizon-linux/amd64
      - load-oci:
          key: minion-linux/amd64
      - load-oci:
          key: sentinel-linux/amd64
      - run:
          name: Monitor JVM processes
          background: true
          command: |
            .circleci/scripts/jvmprocmon-start.sh
      - run:
          name: Monitor memory usage
          background: true
          command: |
            free -m -c 500 -s 30
      - run:
          name: Smoke Tests
          no_output_timeout: 30m
          command: |
            .circleci/scripts/smoke.sh << parameters.suite >>

      - run:
          name: Gather JUnit Output
          when: always
          command: |
            cd smoke-test
            mkdir -p ~/test-results/junit
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
      - store_test_results:
          path: ~/test-results/junit

      - run:
          name: Gather system logs and test artifacts
          when: always
          command: |
            mkdir -p ~/test-artifacts/system-logs
            (dmesg || :) > ~/test-artifacts/system-logs/dmesg 2>&1
            (ps auxf || :) > ~/test-artifacts/system-logs/ps 2>&1
            (free -m || :) > ~/test-artifacts/system-logs/free 2>&1
            (docker stats --no-stream || :) > ~/test-artifacts/system-logs/docker_stats 2>&1
            cp -R /tmp/jvmprocmon ~/test-artifacts/system-logs/ || :
            ls -alh ~/project/smoke-test/ || :

            mkdir -p ~/test-artifacts/recordings
            cp -R ~/project/smoke-test/target/*.flv ~/test-artifacts/recordings/ || true
            cp -R ~/project/smoke-test/target/screenshots ~/test-artifacts/ || true
            cp -R ~/project/smoke-test/target/logs ~/test-artifacts/ || true
      - store_artifacts:
          when: always
          path: ~/test-artifacts
          destination: test-artifacts
