workflows:
  build-deploy:
    when:
      and:
        - equal: [ false, << pipeline.parameters.trigger-coverage >> ]
        - equal: [ true,  << pipeline.parameters.trigger-build >> ]
        - equal: [ false, << pipeline.parameters.minimal >> ]
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /^from-foundation.*/
      - tarball-assembly-only:
          requires:
            - build
      - minion-image-single-arch-linux-amd64:
          context:
            - docker-content-trust
            - azure-sp-dct
          requires:
            - tarball-assembly-only         
      - minion-image-single-arch:
          matrix:
            parameters:
              architecture: [linux/arm64,linux/arm/v7]
          context:
            - docker-content-trust
            - azure-sp-dct
          requires:
            - tarball-assembly-only
            - integration-test
            - smoke-test-core
            - smoke-test-flaky
            - smoke-test-minion
            - smoke-test-sentinel
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^features\/.+/
                - /^foundation.*/
                - /^release-.*/
                - /.*docker.*/
                - /.*smoke.*/
      - minion-image-multi-arch:
          context:
            - docker-content-trust
            - azure-sp-dct
          requires:
            - minion-image-single-arch-linux-amd64
            - minion-image-single-arch
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^features\/.+/
                - /^foundation.*/
                - /^release-.*/
                - /.*docker.*/
                - /.*smoke.*/
      - horizon-image-single-arch:
          requires:
            - tarball-assembly-only
            - integration-test
            - smoke-test-core
            - smoke-test-flaky
            - smoke-test-minion
            - smoke-test-sentinel
          matrix:
            parameters:
              architecture: [linux/arm64]
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^features\/.+/
                - /^foundation.*/
                - /^release-.*/
                - /.*docker.*/
      - horizon-deb-build:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^dependabot\/.*/
                - /^features\/.+/
                - /^foundation.*/
                - /^release-.*/
                - /.*deb.*/
      - minion-rpm-build:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^dependabot\/.*/
                - /^features\/.+/
                - /^foundation.*/
                - /^release-.*/
                - /.*rpm.*/
      - sentinel-rpm-build:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^dependabot\/.*/
                - /^features\/.+/
                - /^foundation.*/
                - /^release-.*/
                - /.*rpm.*/
      - integration-test:
          requires:
            - build
          filters:
            branches:
              ignore:
                - /^merge-foundation.*/
      - smoke-test-core:
          requires:
            - tarball-assembly-only
            - horizon-image-single-arch-linux-amd64
            - sentinel-image-single-arch-linux-amd64
            - minion-image-single-arch-linux-amd64
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^dependabot.*/
                - /^features\/.+/
                - /^foundation.*/
                - /^release-.*/
                - /.*smoke.*/
      - smoke-test-flaky:
          requires:
            - tarball-assembly-only
            - horizon-image-single-arch-linux-amd64
            - sentinel-image-single-arch-linux-amd64
            - minion-image-single-arch-linux-amd64
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^dependabot.*/
                - /^features\/.+/
                - /^foundation.*/
                - /^release-.*/
                - /.*smoke.*/
      - smoke-test-minion:
          requires:
            - tarball-assembly-only
            - horizon-image-single-arch-linux-amd64
            - sentinel-image-single-arch-linux-amd64
            - minion-image-single-arch-linux-amd64
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^dependabot.*/
                - /^features\/.+/
                - /^foundation.*/
                - /^release-.*/
                - /.*smoke.*/
      - smoke-test-sentinel:
          requires:
            - tarball-assembly-only
            - horizon-image-single-arch-linux-amd64
            - sentinel-image-single-arch-linux-amd64
            - minion-image-single-arch-linux-amd64
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^dependabot.*/
                - /^features\/.+/
                - /^foundation.*/
                - /^release-.*/
                - /.*smoke.*/
      - horizon-image-single-arch-linux-amd64:
          requires:
            - tarball-assembly-only
      - horizon-publish-oci:
          requires:
            - integration-test
            - smoke-test-core
            - smoke-test-flaky
            - smoke-test-minion
            - smoke-test-sentinel
            - horizon-image-single-arch-linux-amd64
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^release-.*/
                - /^features\/.+/
                - /^foundation.*/
      - sentinel-publish-oci:
          requires:
            - integration-test
            - smoke-test-core
            - smoke-test-flaky
            - smoke-test-minion
            - smoke-test-sentinel
            - sentinel-image-single-arch-linux-amd64
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^release-.*/
                - /^features\/.+/
                - /^foundation.*/
      - horizon-rpm-build:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^dependabot.*/
                - /^features\/.+/
                - /^foundation.*/
                - /^release-.*/
                - /.*rpm.*/
      - minion-deb-build:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^dependabot\/.*/
                - /^features\/.+/
                - /^foundation.*/
                - /^release-.*/
      - sentinel-deb-build:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^dependabot\/.*/
                - /^features\/.+/
                - /^foundation.*/
                - /^release-.*/
      - sentinel-image-single-arch-linux-amd64:
          requires:
            - tarball-assembly-only
      - sentinel-image-single-arch:
          requires:
            - tarball-assembly-only
          matrix:
            parameters:
              architecture: [linux/arm64]
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^foundation.*/
                - /^release-.*/
                - /.*docker.*/
                - /.*smoke.*/
      - create-merge-foundation-branch:
          # technically only requires the RPM/deb builds, but only publish
          # if everything passes
          requires:
            - horizon-rpm-build
            - minion-deb-build
            - sentinel-rpm-build
            - integration-test
            - smoke-test-core
            - smoke-test-flaky
            - smoke-test-minion
#            - smoke-test-minimal
            - smoke-test-sentinel
          filters:
            branches:
              only: << pipeline.parameters.main_branch >>
      - merge-foundation-branch:
          # technically only requires the RPM/deb builds, but only publish
          # if everything passes
          requires:
            - tarball-assembly-only
          filters:
            branches:
              only: merge-foundation/<< pipeline.parameters.previous_branch_label >>-to-<< pipeline.parameters.main_branch_label >>
      - create-merge-meridian-branch:
          # technically only requires the RPM/deb builds, but only publish
          # if everything passes
          requires:
            - horizon-rpm-build
            - minion-deb-build
            - sentinel-rpm-build
            - integration-test
            - smoke-test-core
            - smoke-test-flaky
            - smoke-test-minion
#            - smoke-test-minimal
            - smoke-test-sentinel
          filters:
            branches:
              only: /^foundation.*/
      - merge-poweredby-branch:
          # technically only requires the RPM/deb builds, but only publish
          # if everything passes
          requires:
            - horizon-rpm-build
            - smoke-test-core
            - smoke-test-flaky
            - smoke-test-minion
            - smoke-test-sentinel
#            - smoke-test-minimal
            - integration-test
          filters:
            branches:
              only:
                - /^foundation.*/
      - publish-cloudsmith:
          # technically only requires the RPM/deb builds, but only publish
          # if everything passes
          requires:
            - horizon-rpm-build
            - minion-deb-build
            - sentinel-rpm-build
            - integration-test
            - smoke-test-core
            - smoke-test-flaky
            - smoke-test-minion
#            - smoke-test-minimal
            - smoke-test-sentinel
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^release-.*/
                - /^foundation.*/
