workflows:
  build-deploy:
    when:
      and:
        - equal: [ false, << pipeline.parameters.trigger-coverage >> ]
        - equal: [ true,  << pipeline.parameters.trigger-build >> ]
        - equal: [ false, << pipeline.parameters.minimal >> ]
        - equal: [ false, << pipeline.parameters.trigger-flaky-tests >> ]
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /^from-foundation.*/
      - tarball-assembly:
          requires:
            - build
      - minion-image-single-arch:
          matrix:
            parameters:
              architecture: [linux/amd64,linux/arm64,linux/arm/v7]
          context:
            - docker-content-trust
            - azure-sp-dct
          requires:
            - rpm-builds
            - minion-deb-build
            - debian-pkg-build
            - integration-test
            - smoke-test-core
            - smoke-test-flaky
            - smoke-test-minion
            - smoke-test-minimal
            - smoke-test-sentinel
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^release-.*/
                - /.*arm64.*/
      - minion-image-multi-arch:
          context:
            - docker-content-trust
            - azure-sp-dct
          requires:
            - minion-image-single-arch
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^release-.*/
                - /.*arm64.*/
      - horizon-image-single-arch:
          requires:
            - debian-pkg-build
          matrix:
            parameters:
              architecture: [linux/arm64]
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^release-.*/
                - /.*arm64.*/
      - rpm-builds:
          requires:
            - integration-test
          filters:
            branches:
              ignore:
                - /^merge-foundation.*/           
      - integration-test:
          requires:
            - build
          filters:
            branches:
              ignore:
                - /^merge-foundation.*/
      - smoke-test-core:
          requires:
            - tarball-assembly
            - rpm-builds
            - debian-pkg-build
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^release-.*/
                - /^foundation.*/
                - /^features.*/
                - /.*smoke.*/
                - /^dependabot.*/
      - smoke-test-flaky:
          requires:
            - tarball-assembly
            - rpm-builds
            - debian-pkg-build
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^release-.*/
                - /^foundation.*/
                - /^features.*/
                - /.*smoke.*/
                - /^dependabot.*/
      - smoke-test-minion:
          requires:
            - tarball-assembly
            - rpm-builds
            - debian-pkg-build
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^release-.*/
                - /^foundation.*/
                - /^features.*/
                - /.*smoke.*/
                - /^dependabot.*/
      - smoke-test-sentinel:
          requires:
            - tarball-assembly
            - tarball-assembly
            - debian-pkg-build
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^release-.*/
                - /^foundation.*/
                - /^features.*/
                - /.*smoke.*/
                - /^dependabot.*/
      - smoke-test-minimal:
          requires:
            - tarball-assembly
            - tarball-assembly
            - debian-pkg-build
          filters:
            branches:
              ignore:
                - develop
                - /^master-.*/
                - /^release-.*/
                - /^foundation.*/
                - /^merge-foundation.*/
                - /^features.*/
                - /.*smoke.*/
                - /^dependabot.*/
      - horizon-publish-oci:
          requires:
            - minion-deb-build
            - debian-pkg-build
            - integration-test
            - smoke-test-core
            - smoke-test-flaky
            - smoke-test-minion
            - smoke-test-minimal
            - smoke-test-sentinel
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^release-.*/
                - /^features\/.+/
      - sentinel-publish-oci:
          requires:
            - minion-deb-build
            - debian-pkg-build
            - integration-test
            - smoke-test-core
            - smoke-test-flaky
            - smoke-test-minion
            - smoke-test-minimal
            - smoke-test-sentinel
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^release-.*/
                - /^features\/.+/
      - minion-deb-build:
          requires:
            - integration-test
          filters:
            branches:
              ignore:
                - /^merge-foundation.*/
      - debian-pkg-build:
          requires:
            - build 
          filters:
            branches:
              ignore:
                - /^merge-foundation.*/          
      - sentinel-image-single-arch:
          requires:
            - debian-pkg-build
          matrix:
            parameters:
              architecture: [linux/arm64]
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^release-.*/
                - /.*arm64.*/
      - create-merge-foundation-branch:
          # technically only requires the RPM/deb builds, but only publish
          # if everything passes
          requires:
            - rpm-builds
            - minion-deb-build
            - integration-test
            - smoke-test-core
            - smoke-test-flaky
            - smoke-test-minion
            - smoke-test-minimal
            - smoke-test-sentinel
          filters:
            branches:
              only: << pipeline.parameters.main_branch >>
      - merge-foundation-branch:
          # technically only requires the RPM/deb builds, but only publish
          # if everything passes
          requires:
            - tarball-assembly
          filters:
            branches:
              only: merge-foundation/<< pipeline.parameters.previous_branch_label >>-to-<< pipeline.parameters.main_branch_label >>
      - create-merge-meridian-branch:
          # technically only requires the RPM/deb builds, but only publish
          # if everything passes
          requires:
            - rpm-builds
            - minion-deb-build
            - integration-test
            - smoke-test-core
            - smoke-test-flaky
            - smoke-test-minion
            - smoke-test-minimal
            - smoke-test-sentinel
          filters:
            branches:
              only: /^foundation.*/
      - merge-poweredby-branch:
          # technically only requires the RPM/deb builds, but only publish
          # if everything passes
          requires:
            - rpm-builds
            - smoke-test-core
            - smoke-test-flaky
            - smoke-test-minion
            - smoke-test-sentinel
            - smoke-test-minimal
            - integration-test
          filters:
            branches:
              only:
                - /^foundation.*/
      - publish-cloudsmith:
          # technically only requires the RPM/deb builds, but only publish
          # if everything passes
          requires:
            - rpm-builds
            - minion-deb-build
            - integration-test
            - smoke-test-core
            - smoke-test-flaky
            - smoke-test-minion
            - smoke-test-minimal
            - smoke-test-sentinel
          filters:
            branches:
              only:
                - develop
                - /^master-.*/
                - /^release-.*/
                - /^foundation.*/

