jobs:
  horizon-image-single-arch-with-trivy-linux-amd64:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: false
    environment:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - build-image-single-arch-with-trivy:
          architecture: linux/amd64
          container_name: horizon
