version: 1
allowed_updates:
  - match:
    update_type: security
ignored_updates:
  - match:
    dependency_name: "ionicons"
update_configs:
  - package_manager: "javascript"
    directory: "/core/web-assets/"
    update_schedule: "weekly"
    default_reviewers:
      - "rangerrick"
      - "j-white"
    default_labels:
      - "dependency update"
    commit_message:
      prefix: "build"
      include_scope: true
