jobs:
  debs-build:
    executor: debian-build-executor
    resource_class: xlarge
    steps:
      - attach_workspace:
          at: ~/
      - sign-packages/setup-env:
          skip_if_forked_pr: true
          gnupg_home: ~/tmp/gpg
      - run:
          name: Monitor memory usage
          background: true
          command: |
            free -m -c 500 -s 30
      - run:
          name: Build OpenNMS Debian Packages
          command: |
            export NODE_OPTIONS=--max_old_space_size=1024
            export CCI_MAXCPU=2
            export MAVEN_OPTS="-Xmx8g -XX:ReservedCodeCacheSize=1g -XX:+TieredCompilation"
            .circleci/scripts/makedeb.sh opennms
      - run:
          name: Build Sentinel Debian Packages
          command: |
            export NODE_OPTIONS=--max_old_space_size=1024
            export CCI_MAXCPU=4
            export CCI_VAADINJAVAMAXMEM=768m
            export MAVEN_OPTS="-Xmx8g -XX:ReservedCodeCacheSize=1g -XX:+TieredCompilation"
            .circleci/scripts/makedeb.sh sentinel
      #- sign-packages/sign-debs:
      #    skip_if_forked_pr: true
      #    gnupg_home: ~/tmp/gpg
      #    gnupg_key: opennms@opennms.org
      #    packages: target/debs/*.deb
      #- run:
      #    name: Gather system logs
      #    when: always
      #    command: |
      #      mkdir -p ~/build-results/system-logs
      #      (dmesg || :) > ~/build-results/system-logs/dmesg 2>&1
      #      (ps auxf || :) > ~/build-results/system-logs/ps 2>&1
      #      (free -m || :) > ~/build-results/system-logs/free 2>&1
      #      (docker stats --no-stream || :) > ~/build-results/system-logs/docker_stats 2>&1
      #      cp -R /tmp/jvmprocmon ~/build-results/system-logs/ || :
      ##- setup_remote_docker:
      #    docker_layer_caching: true
      #- run:
      #    name: Fetch DEB artifacts and build horizon container image
      #    command: |
      #      cd opennms-container/horizon
      #      env DOCKER_ARCH="linux/amd64" ./build_container_image.sh
      #- run:
      #    name: Fetch DEB artifacts and build sentinel container image
      #    command: |
      #      cd opennms-container/sentinel
      #      env DOCKER_ARCH="linux/amd64" ./build_container_image.sh
      #- store_artifacts:
      #    when: always
      #    path: ~/build-results
      #    destination: build-results
      #- store_artifacts:
      #    path: ~/project/target/debs
      #    destination: debs
      #- store_artifacts:
      #    path: ~/project/opennms-container/horizon/images/container.oci
      #    destination: horizon.oci
      #- store_artifacts:
      #    path: ~/project/opennms-container/sentinel/images/container.oci
      #    destination: sentinel.oci
      #- cache-workflow-assets:
      #    cache_prefix: deb-horizon
      #    source_path: target/debs
      #- cache-workflow-assets:
      #    cache_prefix: deb-sentinel
      #    source_path: target/debs
      #- cache-oci:
      #    key: horizon
      #    path: opennms-container/horizon/images/
      #- cache-oci:
      #    key: sentinel
      #    path: opennms-container/sentinel/images/

  horizon-deb-build:
    executor: debian-build-executor
    resource_class: xlarge
    steps:
      - attach_workspace:
          at: ~/
      - sign-packages/setup-env:
          skip_if_forked_pr: true
          gnupg_home: ~/tmp/gpg
      - run:
          name: Monitor memory usage
          background: true
          command: |
            free -m -c 500 -s 30
      - run:
          name: Build Debian Packages
          command: |
            export NODE_OPTIONS=--max_old_space_size=1024
            export CCI_MAXCPU=2
            export MAVEN_OPTS="-Xmx8g -XX:ReservedCodeCacheSize=1g -XX:+TieredCompilation"
            .circleci/scripts/makedeb.sh opennms
      - sign-packages/sign-debs:
          skip_if_forked_pr: true
          gnupg_home: ~/tmp/gpg
          gnupg_key: opennms@opennms.org
          packages: target/debs/*.deb
      - run:
          name: Gather system logs
          when: always
          command: |
            mkdir -p ~/build-results/system-logs
            (dmesg || :) > ~/build-results/system-logs/dmesg 2>&1
            (ps auxf || :) > ~/build-results/system-logs/ps 2>&1
            (free -m || :) > ~/build-results/system-logs/free 2>&1
            (docker stats --no-stream || :) > ~/build-results/system-logs/docker_stats 2>&1
            cp -R /tmp/jvmprocmon ~/build-results/system-logs/ || :
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Fetch DEB artifacts and build horizon container image
          command: |
            cd opennms-container/horizon
            env DOCKER_ARCH="linux/amd64" ./build_container_image.sh
      - store_artifacts:
          when: always
          path: ~/build-results
          destination: build-results
      - store_artifacts:
          path: ~/project/target/debs
          destination: debs
      - store_artifacts:
          path: ~/project/opennms-container/horizon/images/container.oci
          destination: horizon.oci
      - cache-workflow-assets:
          cache_prefix: deb-horizon
          source_path: target/debs
      - cache-oci:
          key: horizon
          path: opennms-container/horizon/images/
  minion-deb-build:
    executor: debian-build-executor
    resource_class: xlarge
    steps:
      - attach_workspace:
          at: ~/
      - sign-packages/setup-env:
          skip_if_forked_pr: true
          gnupg_home: ~/tmp/gpg
      - run:
          name: Build Debian Packages
          command: |
            export NODE_OPTIONS=--max_old_space_size=1024
            export CCI_MAXCPU=4
            export CCI_VAADINJAVAMAXMEM=768m
            export MAVEN_OPTS="-Xmx8g -XX:ReservedCodeCacheSize=1g -XX:+TieredCompilation"
            .circleci/scripts/makedeb.sh minion
      - sign-packages/sign-debs:
          skip_if_forked_pr: true
          gnupg_home: ~/tmp/gpg
          gnupg_key: opennms@opennms.org
          packages: target/debs/*.deb
      - store_artifacts:
          path: ~/project/target/debs
          destination: debs
      - cache-workflow-assets:
          cache_prefix: deb-minion
          source_path: target/debs
  sentinel-deb-build: 
    executor: debian-build-executor
    resource_class: xlarge
    steps:
      - attach_workspace:
          at: ~/
      - sign-packages/setup-env:
          skip_if_forked_pr: true
          gnupg_home: ~/tmp/gpg
      - run:
          name: Build Debian Packages
          command: |
            export NODE_OPTIONS=--max_old_space_size=1024
            export CCI_MAXCPU=4
            export CCI_VAADINJAVAMAXMEM=768m
            export MAVEN_OPTS="-Xmx8g -XX:ReservedCodeCacheSize=1g -XX:+TieredCompilation"
            .circleci/scripts/makedeb.sh sentinel
      - sign-packages/sign-debs:
          skip_if_forked_pr: true
          gnupg_home: ~/tmp/gpg
          gnupg_key: opennms@opennms.org
          packages: target/debs/*.deb
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Fetch DEB artifacts and build sentinel container image
          command: |
            cd opennms-container/sentinel
            env DOCKER_ARCH="linux/amd64" ./build_container_image.sh
      - store_artifacts:
          path: ~/project/target/debs
          destination: debs
      - store_artifacts:
          path: ~/project/opennms-container/sentinel/images/container.oci
          destination: sentinel.oci
      - cache-workflow-assets:
          cache_prefix: deb-sentinel
          source_path: target/debs
      - cache-oci:
          key: sentinel
          path: opennms-container/sentinel/images/