[template]
src = "timeseries.properties.tpl"
dest = "/opt/opennms/etc/rrd-configuration.properties"
keys = [
    "opennms/timeseries/strategy",
    "opennms/rrd/storebyforeignsource",
    "opennms/rrd/strategyclass",
    "opennms/rrd/interfacejar",
    "opennms/library/jrrd2"
]
